### ISSUE TITLE
Export Distro Service shares database with Core Data

### ISSUE THREAD

**Issue by trcox** [edgexfoundry/export-distro#20]
https://github.com/edgexfoundry/export-distro/blob/1d8fdf6d7fbb1a9ba650923fa928cedefc11567a/src/main/resources/application.properties#L52

Introduces tight microservice coupling.

Identified with @drasko.

**Comment by tonyespy** [comment]
AFAIK, core-metadata also shares the same instance...

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
