### ISSUE TITLE
Senders are not using protocol to compose the URI

### ISSUE THREAD

**Issue by chenchix** [edgexfoundry/export-distro#22]
According to the Addressable structure, there is a "protocol" parameter. I understand this is used to create the whole URI, right? In MQTTSender (I.E), it is not being used but added in the address.

`            client = new MqttClient(brokerUrl + ":" + brokerPort, clientId);
`
to 

`            client = new MqttClient(brokerProtocol+"://"+brokerUrl + ":" + brokerPort, clientId);
`

or something like that.

**Comment by trcox** [comment]
Direct reference for tracking: https://github.com/edgexfoundry/export-distro/blob/ffd894f17c94ce965f1e483ebaabef957823810d/src/main/java/org/edgexfoundry/messaging/MQTTSender.java#L98

Required to fully support MQTTS port change in #18.
