### ISSUE TITLE
Implement AWS IoT Export Service

### ISSUE THREAD

**Issue by janko-isidorovic** [edgexfoundry/export-distro#31]
We want to create export service which will allow EdgeX to export device data to Amazon AWS IoT.

**Comment by feclare** [comment]
The idea is to have a new export service or to integrate it with export distro?

**Comment by jpwhitemn** [comment]
Hi Fede - I think this entry was created by Janko as he was experimenting with the use of GitHub issues and GitHub Projects.  So I don't think this was meant to be an immediate need (but I will check with Janko).
In general, at some point, we do want to offer an export (via export distro) to AWS IoT just like we have for Azure IoT Hub and Google IoT Core. 

    On Thursday, October 26, 2017, 2:53:31 AM CDT, Fede Claramonte <notifications@github.com> wrote:  
 
 
The idea is to have a new export service or to integrate it with export distro?

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
