### ISSUE TITLE
rest server do not receive messages

### ISSUE THREAD

**Issue by lesliechung88** [edgexfoundry/export-distro#44]
export-distro/src/main/java/org/edgexfoundry/serviceactivator/RESTOutboundServiceActivator.java line 58 

		Message<String> message = MessageBuilder.withPayload(exportString.getEventString()).build(); 
	should be :
			Message<String> message = MessageBuilder.withPayload(exportString.getEventString()).**setHeader(MessageHeaders.CONTENT_TYPE, MimeTypeUtils.APPLICATION_JSON_VALUE).**build();

**Comment by eb-oss** [comment]
Closing issue; project is being archived.
