### ISSUE TITLE
registered client with mqtt protocol is not receiving err

### ISSUE THREAD

**Issue by rajnishkumar9250** [edgexfoundry/export-distro#46]
A client registered with MQTT protocol not receiving data. Getting below error message  
ClientMessageSplitter: problem splitting messages per client request:  No enum constant org.edgexfoundry.domain.common.HTTPMethod.

But Its working for HTTP. My data for registered client for mqtt is below

{
    "_id" : ObjectId("5c3c723cfd4ca80001a5af1e"),
    "created" : NumberLong(1547465276365),
    "modified" : NumberLong(0),
    "origin" : NumberLong(0),
    "name" : "140119457MqttPublisher",
    "addressable" : {
        "created" : NumberLong(0),
        "modified" : NumberLong(0),
        "origin" : NumberLong(0),
        "name" : "140119457myMqttBroker",
        "protocol" : "TCP",
        "method" : "",
        "address" : "192.168.1.106",
        "port" : 1883,
        "path" : "",
        "publisher" : "EdgeXExportPublisher",
        "user" : "",
        "password" : "",
        "topic" : "clienttopic"
    },
    "format" : "JSON",
    "filter" : {},
    "encryption" : {
        "encryptionAlgorithm" : "NONE"
    },
    "compression" : "NONE",
    "enable" : true,
    "destination" : "MQTT_TOPIC"
}

I have tested with multiple for protocol, nothing has worked. I have tried following
protocole: TCP, tcp, OTHER
address: hostname, tcp://hostname, TCP://hostname

nothing worked

**Comment by tsconn23** [comment]
FYI -- This service has been converted to Go and is now part of the [edgex-go ](https://github.com/edgexfoundry/edgex-go) repo. No updates are planned for this repo.
