### ISSUE TITLE
org.edgexfoundry.transformer.SerializedFormatTransformerTest testTransform test is failing.

### ISSUE THREAD

**Issue by feclare** [edgexfoundry/export-distro#9]
Ubuntu 17.04
$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)

content of file target/surefire-reports/org.edgexfoundry.transformer.SerializedFormatTransformerTest.txt
-------------------------------------------------------------------------------
Test set: org.edgexfoundry.transformer.SerializedFormatTransformerTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.027 sec <<< FAILURE! - in org.edgexfoundry.transformer.SerializedFormatTransformerTest
testTransform(org.edgexfoundry.transformer.SerializedFormatTransformerTest)  Time elapsed: 0.015 sec  <<< FAILURE!
org.junit.ComparisonFailure: Serialized tranformed string not the same as the expected string expected:<...bWFpbi5jb3JlLkV2ZW50[E6n2aFF621YCAANKAAZwdXNoZWRMAAZkZXZpY2V0ABJMamF2YS9sYW5nL1N0cmluZztMAAhyZWFkaW5nc3QAEExqYXZhL3V0aWwvTGlzdDt4cgApb3JnLmVkZ2V4Zm91bmRyeS5kb21haW4uY29tbW9uLkJhc2VPYmplY3TslRflPrMt4w]IABEoAB2NyZWF0ZWRKAA...> but was:<...bWFpbi5jb3JlLkV2ZW50[gyv7XbhoXaYCAANKAAZwdXNoZWRMAAZkZXZpY2V0ABJMamF2YS9sYW5nL1N0cmluZztMAAhyZWFkaW5nc3QAEExqYXZhL3V0aWwvTGlzdDt4cgApb3JnLmVkZ2V4Zm91bmRyeS5kb21haW4uY29tbW9uLkJhc2VPYmplY3T8ogM99zuWWQ]IABEoAB2NyZWF0ZWRKAA...>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.edgexfoundry.transformer.SerializedFormatTransformerTest.testTransform(SerializedFormatTransformerTest.java:53)

**Comment by jpwhitemn** [comment]
This issue is due to change of parameternames to parameterNames in metadata command serializer in metadata.  Just needs to be updated to use proper result string for comparison. Probably also needs to be setup so that it is not hardcoded.

**Comment by jpwhitemn** [comment]
Bug fix submit that addresses
